import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { ClientProviders } from "@/context/ClientProviders";
import "modern-normalize";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Games Tournaments",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  antialiased flex min-h-screen flex-col items-center bg-white dark:bg-black`}
      >
        <ClientProviders children={children} modal={modal} />
      </body>
    </html>
  );
}
